window.team = [
   {
     name: "Marc-André Ter Stegen",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/e2eb4798-1d81-45f0-8aae-34007129ca25/01-Ter_Stegen.png?width=670&height=790",
     number: "1",
     position: "Goalkeeper",
     age: "33",
     nationality: "Germany",
     bio: "Marc-André ter Stegen signed for FC Barcelona in the summer of 2014 from Borussia Mönchengladbach. Born on 30 April 1992 in Mönchengladbach itself, the German did not take long to make his name as one Europe’s most promising young goalkeepers.",
   },
   {
     name: "Joan Garcia",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/81c7699c-1298-45d6-834e-df72d8c550c8/01-Joan_Garcia.png?width=670&height=790",
     number: "13",
     position: "Goalkeeper",
     age: "24",
     nationality: "Spain",
     bio: "Joan Garcia came to FC Barcelona in the summer of 2025 after showing himself to be one of the best goalkeepers in La Liga in the previous campaign. ",
   },
   {
     name: "Wojciech Szczęsny",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/adf97c66-a953-4225-a772-eb6c0258ed2b/25-Szczesny.png?width=670&height=790",
     number: "25",
     position: "Goalkeeper",
     age: "35",
     nationality: "Poland",
     bio: "FC Barcelona and the player Wojciech Szczęsny reached an agreement for him to join the Club until 30 June 2025 after Ter Stegen picked up a long-term injury.",
   },
   {
     name: "Alejandro Balde",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/0d332686-2eee-4297-a099-bab75c7c35bb/03-Balde.png?width=670&height=790",
     number: "3",
     position: "Defender",
     age: "22",
     nationality: "Spain",
     bio: "Alejandro Balde, born in Barcelona to Guinean and Dominican parents, is a fast and explosive full back who joined Barça in 2011 at the age of eight after coming up through ranks at Espanyol.",
   },
   {
     name: "Ronald Araujo",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/072afc10-1ec9-483e-a4a5-8775cb6cea23/04-Araujo.png?width=670&height=790",
     number: "4",
     position: "Defender",
     age: "25",
     nationality: "Uruguay",
     bio: "Ronald Araujo was born in Rivera, Uruguay, on 7 March 1999. The young central defender began playing professionally for his hometown team, and later joined the lower categories at Rentistas in the Uruguayan Second Division.",
   },
   {
     name: "Pau Cubarsí",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/8c77ff44-6a20-4b1f-9991-bb3937af9ce4/02-Cubarsi.png?width=670&height=790",
     number: "5",
     position: "Defender",
     age: "18",
     nationality: "Spain",
     bio: "Pau Cubarsí arrived at La Masia from Girona on 1 July 2018 as a U12 player. The 2023/24 season was a key moment in his career as he made his competitive debut with the first team",
   },
   {
     name: "Andreas Christensen",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/d2083355-8ef0-4398-94ae-7d84615de3c2/15-Christensen.png?width=670&height=790",
     number: "15",
     position: "Defender",
     age: "29",
     nationality: "Denmark",
     bio: "An excellent reader of the game and versatile centre back, Andreas Christensen (10 April 1996) was born in Lillerød (Denmark) where he started out at IF Skjold Birkerød, soon catching the eye of Brøndby IF.",
   },
   {
     name: "Gerard Mart",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/a4ea019d-b5b3-4b6e-a970-79fe8afc8bfd/18-Martin.png?width=670&height=790",
     number: "18",
     position: "Defender",
     age: "23",
     nationality: "Spain",
     bio: "Gerard Martín began his career at EF Performance and Sant Gabriel before moving at the U19 level to UE Cornellà where he reached the senior team in 2021/22. A defender who stands out for his versatility at the back. Even though he is a natural left back, he is tall enough to slot in at centre back if needed",
   },
   {
     name: "Jules Kounde",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/089a6980-e8be-46fe-900c-4202293ef729/23-Kounde.png?width=670&height=790",
     number: "23",
     position: "Defender",
     age: "26",
     nationality: "France",
     bio: "Jules Kounde was born in Paris on November 12, 1998. His family originally came from Benin. He started playing for small clubs in the outskirts of Bordeaux in Southwest France. He first passed a trial at the age of 14 years old and joined the youth ranks of the professional team, FC Girondins de Bordeaux.",
   },
   {
     name: "Eric Garcia",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/bbfb1ea9-ad02-466c-80ba-ab2da4c3ce25/24-Eric_Garcia.png?width=670&height=790",
     number: "24",
     position: "Defender",
     age: "24",
     nationality: "Spain",
     bio: "A player of massive potential, he is the classic Barça defender. He likes to play the ball out of with his feet, is extremely smart at reading his opponents’ moves and reads the game with instinctive precision. Eric Garcia returned to Barça in the summer of 2021 from Manchester City. He originally joined the Barça Escola in 2008 and resided at La Masia until 2017. ",
   },
   {
     name: "Gavi",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/7f610def-b5e6-46ce-9891-9e6988b89e29/06-Gavi.png?width=670&height=790",
     number: "6",
     position: "Midfielder",
     age: "21",
     nationality: "Spain",
     bio: "A combative and technically gifted midfielder Pablo Páez Gavira, better known as 'Gavi', was born in the town of Los Palacios y Villafranca near Seville. As a youngster he made his way to the youth system at Real Betis where he spent two seasons representing the verdiblancos at the Luis del Sol training complex just a stone's throw from the Benito Villamarín stadium. ",
   },
   {
     name: "Pedri",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/3dd2346c-01bb-4ad9-9b62-ed5cbf8d8b06/08-Pedri.png?width=670&height=790",
     number: "8",
     position: "Midfielder",
     age: "22",
     nationality: "Spain",
     bio: "On September 2, 2019, FC Barcelona and Las Palmas reached an agreement for the transfer of Pedri. However, the Canarian player didn't join the blaugranes until August 2020. Born in Tegueste, Tenerife, on November 25, 2002, he began his football career in the team from his hometown. ",
   },
   {
     name: "Fermín López",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/133e2b63-bc19-4d56-8e10-661ff5270823/16-Fermin.png?width=670&height=790",
     number: "16",
     position: "Midfielder",
     age: "22",
     nationality: "Spain",
     bio: "Fermín López Marín was part of the Campillo youth setup in his home town, and then signed for Recreativo Huelva. After one season, in 2011/12 he moved to Real Betis Balompié and four years later entered La Masía as an U14.",
   },
   {
     name: "Marc Casadó",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/962219f5-5db9-45e1-95a6-50c6329ed2ac/17-Casado.png?width=670&height=790",
     number: "17",
     position: "Midfielder",
     age: "22",
     nationality: "Spain",
     bio: "Born in Sant Pere de Vilamajor in 2003 and a defensive central midfielder who provides a lot of balance to the team, Marc Casadó left Damm to join the Club for the 2016 season. The Catalan midfielder has stood out throughout his time in youth development at Barça, becoming one of the leaders of the squad.",
   },
   {
     name: "Dani Olmo",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/eec9fdad-d078-4780-b0c3-4d9fe2f3b328/20-Olmo.png?width=670&height=790",
     number: "20",
     position: "Midfielder",
     age: "27",
     nationality: "Spain",
     bio: "An attack minded forward who can play anywhere up front and in midfield Dani Olmo, born on 7 May 1998 in Terrassa, Catalonia, arrived at La Masia in 2007 from neighbours Espanyol and after seven years in the blaugrana youth system, the Catalan decided to further his career in Croatia, signing for Dinamo Zagreb.  ",
   },
   {
     name: "Frenkie De Jong",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/b62d13a8-5712-4823-b627-18dcce921378/21-De_Jong.png?width=670&height=790",
     number: "21",
     position: "Midfielder",
     age: "28",
     nationality: "Netherlands",
     bio: "Frenkie de Jong was born in Arkel (Netherlands) on May 12, 1997. The Barça player started his career at Willem II in the Eredivise, the Dutch first division. In 2016 he signed for Ajax, where he gradually gained a place in the starting eleven. His versatility and his great vision allowed him to become the midfield organiser for the team from Amsterdam.",
   },
   {
     name: "Marc Bernal",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/a4f602c5-5476-4db3-9148-0a6fee1767fb/22-Bernal.png?width=670&height=790",
     number: "22",
     position: "Midfielder",
     age: "18",
     nationality: "Spain",
     bio: "Born in Berga in Catalonia on 26 May, 2007, Marc Bernal Casas started his career with his home town club before joining Barça and La Masia at the age of just six. As a youngster his talent was obvious and Bernal quickly moved through the age categories. ",
   },
   {
     name: "Ferran Torres",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/05ad9394-0706-4043-8315-1795193f17ad/07-Ferran_Torres.png?width=670&height=790",
     number: "7",
     position: "Forward",
     age: "25",
     nationality: "Spain",
     bio: "Born on 29 February 2000 in Foios (Valencia), Ferran Torres made first contact with the ball at an early age. He started out with futsal at the EPLA school and then attracted the attention of the Valencia CF academy. He was only seven years when he wore the shirt for the first time.",
   },

   {
     name: "Robert Lewandowski",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/3f98839a-bac3-451e-9431-6d58b79588d5/09-Lewandowski.png?width=670&height=790",
     number: "9",
     position: "Forward",
     age: "37",
     nationality: "Poland",
     bio: "The striker from Poland stands out for his goalscoring abilities. Inside the box he has all the tools to make him a difficult striker to read as he can find the net with his head and both feet with equal precision. ",
   },

   {
     name: "Lamine Yamal",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/aae1899c-adb7-450a-b705-61cad72d2508/10-Lamine.png?width=670&height=790",
     number: "10",
     position: "Forward",
     age: "18",
     nationality: "Spain",
     bio: "Lamine Yamal arrived at FC Barcelona at the age of 7 from his local club CF La Torreta. At La Masia he raced through the age categories quicker than any other player of his generation. Lamine Yamal stands out for his ability to take players on, create chances and for his versatility as he can play as a striker, attacking midfielder or on the right wing. ",
   },
   {
     name: "Raphinha",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/369f0d8e-3301-4f3d-9507-246371f8e3d2/11-Raphinha.png?width=670&height=790",
     number: "11",
     position: "Forward",
     age: "28",
     nationality: "Brazil",
     bio: "A technically proficient winger, with good dribbling, decision making and  an appealing and attractive style of play Raphael Dias Belloli (Raphinha) was born on 14 December 1996 in Porto Alegre, Brazil. He joined the Club from Leeds United in summer 2022.",
   },
   {
     name: "Marcus Rashford",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/6e30bc77-d2b9-4c6f-9a93-6a55628c4d5b/14-Rashford.png?width=670&height=790",
     number: "14",
     position: "Forward",
     age: "28",
     nationality: "England",
     bio: "In July 2025 FC Barcelona and Manchester United reached an agreement for the loan of Marcus Rashford, the English striker becoming part of Hansi Flick's squad. ",
   },
   {
     name: "Roony Bardghji",
     image: "https://www.fcbarcelona.com/photo-resources/2025/09/09/9b946f2d-3dc7-4c96-ab7c-4a0e36e679cf/28-Bardghji.png?width=670&height=790",
     number: "28",
     position: "Forward",
     age: "19",
     nationality: "Sweden",
     bio: "FC Barcelona and FC Copenhagen came to an agreement for the transfer of Roony Bardghji in the summer of 2025. The Swedish player became another young talent on the Barça books after his move to the Catalan capital. ",
   },
  ]
  window.coaches = [
    {
      name: "Hansi Flick",
      photo: "https://www.fcbarcelona.com/photo-resources/2025/09/09/6b074293-dfb2-4f25-a0e3-3c02b351d730/00-Hansi_Flick.jpg?width=1200&height=750",
      coach: "Head Coach",
      age: "60",
      nationality: "Germany",
    }
  ]
  window.matches = [
    {
      date: "2-11-25",
      opponent: "Elche",
      time: "18:30",
      score: "3-1",
      place: "Olympic Stadium, Barcelona",
      competition: "La Liga",

    },
    {
      date: "5-11-25",
      opponent: "Club Brugge",
      time: "21:00",
      score: "",
      place: "Olympic Stadium, Barcelona",
      competition: "UCL",
    },
    {
      date: "9-11-25",
      opponent: "Celta",
      time: "21:00",
      score: "",
      place: "Estadio Abanca Balaídos, Vigo",
      competition: "La Liga",
    },
    {
       date: "22-11-25",
       opponent: "Athletic Club",
       time: "16:50",
       score: "",
       place: "Olumpic Stadium, Barcelona",
       competition:"La Liga",
    },
    {
       date: "25-11-25",
       opponent: "Chelsea",
       time: "21:00",
       score: "",
       place: "Stemford Bridge, London",
       competition:"UCL",
    },
    {
       date: "29-11-25",
       opponent: "Alaves",
       time: "16:15",
       score: "",
       place: "Olympic Stadium, Barcelona",
       competition:"La Liga",
    },
  ]
  window.news = [
    {
      datum: "03-10-25",
      id: 1,
      title: "Barcelona 3-1 Elche",
      image: "https://e0.365dm.com/25/11/1600x900/skysports-rashford-barcelona_7070183.jpg?20251102205936",
      text: '<h3>Barcelona wins and takes second place in La Liga.</h3><br><h4>First half</h4><p>In the first half was Barcelona dominating, and showing it by the goal at 9 minite from Lamine Yamal, who was assisted by Balde.<br> Right two minutes after Ferran Torres scored his 50 goal for Barcelona, and doubled the score. The assist to Torres was given by Fermin Lopez. <br>On 42 minute R.Mir scored goal against Barca. The fist half was ended 2-1 for Barcelona.</p><br><h4>Second half</h4><p>Second half began with goal from Marcus Rashford, who was assisted by Fermin Lopez.<br>5 minutes after Fermin Lopez was replaced by Dani Olmo. It was 50 match for Olmo in Barca. The match enden with 3-1 for Barcelona.</p><br><img class="news-img" src="https://www.fcbarcelona.com/photo-resources/2025/11/02/ab626274-b00a-47dd-8273-e85a6e0ed3c0/_MGA0759.jpg?width=1200&height=750"><p>The player of the match is Fermin Lopez, who gave 2 assists this match.</p><br><p><strong>Highlights of the match: </strong></p><ul><li>⚽ 9 minute - Lamine Yamal (Balde)</li><li>⚽ 11 minute - Ferran Torres (Fermin Lopez)</li><li>⚽ 42 minute - Mir (Elche)</li><li>⚽ 61 minute - Marcus rashford (Fermin Lopez)</li></ul><p><a href="https://youtu.be/2noopVNNxdo?si=D318wveKixw2_eqW" title="Click on me!">Video highlights</a> of the match Barcelona - Elche.</p>',
    },
    {
      datum: "03-10-25",
      id: 2,
      title: "Hansi Flick: 'I'm happy, but we can improve'",
      image: "https://www.fcbarcelona.com/photo-resources/2025/11/02/710b7262-9b97-4ab5-a002-a4eb3555bff0/_MGA8613.jpg?width=1200&height=750",
      text: `
       <h3>Coach happy with many things in the win against Elche, while emphasising he saw some things the team didn't do well</h3>
       <p>"I saw many things we did well, but I also saw some we didn't do well," explained Hansi Flick after the team won 3-1 against Elche to get back on track. 
       It was a tough match, but it meant the three points were earned, and he went on to say: 
       "We have to improve. We are more confident with this victory, it is another step, but we have to continue. 
       I am happy and we have to think positively about the games to come."</p>
       <img class="news-img" src="https://www.football-espana.net/wp-content/uploads/2025/11/Flick-pre-Elche-2.jpeg">
       <pThe match was definitely not easy, which the coach highlighted in the prematch press conference, stating "I like how Elche use the ball and also how they press with a lot of intensity". Both FC Barcelona and Elche made a lot of chances and more could have been scored as Hansi Flick mentioned, who always examines how they can be better in each game.></p>
       <br><p>That involves progressing as a group and individually, and when asked about specific names, he said that they can take another step, such as Fermín: "He can still give more. He is a good player for us, he is very active. He is always there when creating chances and scoring goals". The German coach was also happy with the work done by Marcus Rashford and Frenkie de Jong – two "important" parts of the team.</p>
       <br><p>After this win, Hansi Flick is already looking forward to the upcoming challenges before the next international break in November. "We want to win in the Champions League and then in Vigo to take more steps forward. We have to be positive. I am happy with the victory against Elche", confessed a contented Flick, albeit always with the mindset of developing with each game.</p>
      `, 
    }
  ]
